version: "3.9"

services:
  payment_ui:
    build:
      context: ./payment_ui
      dockerfile: Dockerfile
    container_name: payment_ui
    ports:
      - "4200:4200"

  payment_api:
    build:
      context: ./payment_api/
      dockerfile: Dockerfile
    container_name: payment_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
